### ISSUE TITLE
Fig. 6. Time history of covariance for Case 1.

### ISSUE THREAD

**Issue by reyhanergun** [rhymesg/Particle_Filter#1]
I want to reproduce Fig. 6. Time history of covariance for Case 1.
I run the original code to get results for case1 setting and I used 1000 particles, only for PF for simplicity. But my result is different than the result provided in Fig6 in the paper. In Fig6 covariance is small but in my result covariance is not small and there are fluctuations, i.e., covariance is not decreasing by the simulation time. How can i reproduce the original result presented in Fig6?

**Comment by rhymesg** [comment]
Thank you for showing interest in the paper. I'm afraid I would not be able to run the code today. But I guess if the covariance is big and the RMSE is not, it is possibly because of the filter setting:

`% filter setting`
`sig_init = 40;      % std for initial P`
`sig_proc = 8;       % std for Q`
`sig_meas = 25;      % std for R`

Tuning the filter by manipulating these values would help. I guess decreasing sig_proc to 4 or something would give better results.

And I couldn't upload the original DEM due to security reason, so the results would not be the same with the paper.

**Comment by rhymesg** [comment]
Also, I found that I omitted the DEM resolution setting at the uploaded code. I hope setting like the following works for you.
`%% setting`
`load('../DEM/DB_part.mat')`
`DEM.resolution = 30;`

**Comment by reyhanergun** [comment]
Thank you very much for your quick response. Setting sig_proc to 4 worked for me, now time history of covariance for Case 1 is decreasing.

DEM.resolution = 30; is also loaded by 'DB_part.mat', it is not ommitted, it works fine.
